# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c046730e13edff38f3129f241e89a2f0cff35d576abadb9b07eddf9088378cf9afb5336b678b0b1259f8bf115b4d36c813ce9f4f463c48b2d6788bbbaf0bee4c

test:
  secret_key_base: e8faba1141a7cc60564706703c62ff1beaa1930734bbbac26a91f5f96b2845f7c7829d9594d364c9dd1e3616beab028bac52a8bc5d88e7b56a6a3a7186a1dac5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
